
steps:
  - name: gcr.io/cloud-builders/docker
    args: 
      - build
      - -t
      - europe-docker.pkg.dev/${PROJECT_ID}/cr-seid-zueinander-eu/cr-seid-zueinander-eu:latest
      - .
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - push
      - europe-docker.pkg.dev/${PROJECT_ID}/cr-seid-zueinander-eu/cr-seid-zueinander-eu:latest
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: 
      - run
      - deploy
      - run-seid-zueinander-euwest1
      - --image
      - europe-docker.pkg.dev/${PROJECT_ID}/cr-seid-zueinander-eu/cr-seid-zueinander-eu:latest
      - --region
      - europe-west1
      - --platform
      - managed
      - --port
      - '80'
      - --max-instances
      - '1'
      - --cpu
      - '1'
      - --allow-unauthenticated

images:
  - europe-docker.pkg.dev/${PROJECT_ID}/cr-seid-zueinander-eu/cr-seid-zueinander-eu:latest